### ISSUE TITLE
Error with downloading some Apps

### ISSUE THREAD

**Issue by mohsinjuni** [Akdeniz/google-play-crawler#1]
I am using default code and in TestGooglePlay.java file, there is one method testBulkDetails() which downloads details for following packages.

"com.mobulasoft.criticker",
                                                                            "com.cricbuzz.android",
                                                                            "com.sticksports.stickcricket",
                                                                            "com.indiagames.cricketfever".

But the problem is it only downloads information about first two packages, not for the last two ones. I have tried to debug the code what could have been a problem. The reason I found was that 

service.details() and service.bulkdetails() methods cannot fetch version and installation size information about the packages from Google Play. Any idea, what should I try else? Thanks.

**Comment by Akdeniz** [comment]
Hi @mohsinjuni 

I think those two apps are filtered by Google because of not being compatible with device properties I used within checkin mechanism.(actually that properties were belonged to android emulator :p)

I updated the code to use Galaxy S3 device properties! 

Can you try again and let me know if this issue still continues?

Thanks.

**Comment by mohsinjuni** [comment]
Thanks for updating the code. I have tested it by searching for 'mp3 player' and downloading 10 apps in a loop. It is working perfectly. =) . Thanks again.
