### ISSUE TITLE
service.bulkDetails(packageNames) doesn't return developer's name and email

### ISSUE THREAD

**Issue by Artgit** [Akdeniz/google-play-crawler#13]
Is it possible to get developer's information, for example name and email via service.bulkDetails(packageNames).

I tried following code and it always empty (except packageName):

BulkDetailsResponse bulkDetails = service.bulkDetails(packageNames);
        List<BulkDetailsEntry> bulkDetailsEntryList = bulkDetails.getEntryList();
        for (BulkDetailsEntry bulkDetailsEntry : bulkDetailsEntryList) {
            DocV2 docV2 = bulkDetailsEntry.getDoc();
            DocumentDetails docDetails = docV2.getDetails();
            AppDetails appDetails = docDetails.getAppDetails();
            System.out.println(appDetails.getPackageName());
            System.out.println(appDetails.getDeveloperName());
            System.out.println(appDetails.getDeveloperEmail());
        }

but with a single call like this:

```
    DetailsResponse details = service.details(packageNames.get(0));
    AppDetails appDetails = details.getDocV2().getDetails().getAppDetails();
    System.out.println(appDetails.getDeveloperName());
    System.out.println(appDetails.getDeveloperEmail());
```

everything works fine.

Is it possible to get developers bulk details ? 
Thanks.

**Comment by Akdeniz** [comment]
@Artgit,

I just checked the server response in case there is a parsing problem but it showed up that server does not return such an information for _bulkDetails_ API.

protobuf files belongs this API were generated automatically so there can be problematic and missing parts. You can always check server's response by firing up a proxy and if such information is shown there but can not be reached from GooglePlayAPI, protobuf files can be fixed accordingly. Otherwise there is not much, that I can do ;)

Cheers,
Akdeniz

**Comment by Artgit** [comment]
@Akdeniz, sure, thank you !
